version: '3.4'

networks:
  dev:
    driver: bridge

services:
  duserhandlerapi:
    image: docker.io/library/duserhandlerapi
    depends_on: 
        - "app_db"
    container_name: "userhandlerapi-services"
    ports:
        - "8088:80" 
    build: 
        context: .
        dockerfile: Docker
    environment:
        - ConnectionStrings__DefaultConnection=User ID=postgres:Password=admin;Server=app_db;Port=5433;Database=dbusers; IntegratedSecurity=true;
        - ASPNETCORE_URLS=http://+:80
    networks:
        - dev

  app_db: 
    image: postgres:latest
    container_name: app_db
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=admin
        - POSTGRES_DB=dbusers
    ports:
        - "5433:5432"
    restart: always
    volumes:
        - app_data:/var/lib/postgresql/_data
    networks:
        - dev

volumes: 
  app_data:
  
  
